import os
from azure.identity import DefaultAzureCredential


SUBSCRIPTION_ID = os.environ["SUBSCRIPTION_ID"]
azure_credential = DefaultAzureCredential()

ML_RESOURCE_GROUP_NAME = os.environ["ML_RESOURCE_GROUP_NAME"]
DATABRICKS_RESOURCE_GROUP_NAME = os.environ["DATABRICKS_RESOURCE_GROUP_NAME"]
PREFERED_RESOURCE_LOCATION = os.environ["PREFERED_RESOURCE_LOCATION"]
DEFAULT_RESOURCE_LOCATION = os.environ["DEFAULT_RESOURCE_LOCATION"]
