import os


SUBSCRIPTION_ID = os.environ["SUBSCRIPTION_ID"]
PREFERED_RESOURCE_LOCATION = os.environ["PREFERED_RESOURCE_LOCATION"]
DEFAULT_RESOURCE_LOCATION = os.environ["DEFAULT_RESOURCE_LOCATION"]
MAIN_STORAGE_ACCOUNT_ACCESS_KEY = os.environ["MAIN_STORAGE_ACCOUNT_ACCESS_KEY"]
